### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by petrioski** [tire95/Vicipaedia-Arcanum#1]
Projekti ladattu ti 2.6.2020 klo 20.58

Lähdekoodin käynnistys virtuaaliympäristössä ja requirements.txt latauksen avulla onnistui ongelmitta.

Vau, aika hieno kirjautumissivu - hyvä ensivaikutelma!

Käyttötapaukset, kuten rekisteröinti ja kirjautuminen, haut, kampanjan suojaukset ja useampaan kampanjaan liittyminen  onnistuivat hyvin.

Templaten koodeissa puuttuu listaukset validoinnin virheilmoituksille lomakkeissa (new npcs, creature). Nyt käytännössä liian pitkät tai lyhyet kentät ei anna käyttäjälle virheilmoituksia - submittaus ei vain mene läpi. "Pop-up" notifikaatio tulee, jos kenttä on tyhjä - muuten ei ilmoituksia. 

Koodipuolella lomakkeet näyttää hyviltä - lomakekenttien että ohjeistus on toteutettu placeholderilla. Käytännössä törmäsin pikkujippoon, joka voi olla hyvä huomioda. Esim. Create campaign-sivulla lomakkeessa vaikuttaa siltä, ettei käyttäjälle ei lue mitä tietoja halutaan täytettäväksi, sillä chrome ylikirjoitti nämä ehdottaessaan tallennettuja käyttäjänimeä ja salasanaa. Toisaalta tulevat kyllä näkyviin, kun poistaa esitäytetyt tiedot, et siinä mielessä detalji-tason huomio.

Campaign front pagen käytetävyydestä: käyttäjänä siirtymää hakeutui tekstin kohdalle, jota intuitiivisesti luulin linkiksi. Linkki onkin kuva (jota ei siis vielä ole enkä löytänyt miten lisätään, ominaisuus ehkä tulossa). Laittaisin linkin myös teksteihin NPC ja Creatures.

Yläbanneri - linkki ei toimi - ohjautuu aina kunkin sivun mukaisesti virheosoitteeseen, esim kampanjaa katsellessa yläpalkin osoite on http://127.0.0.1:5000/campaigns/1/index.html, mistä aiheutuu  Not Found -error.

Yleisesti ottaen noodin muuttujat on nimetty selkeästi eikä turhaa kommentoitia tai debuggausta ole jätetty - harjoitustyö on varsin valmiin oloinen. Kansiorakenne on hyvä ja kurssimateriaalin mukainen. Mielestäni luokkakaavio toimii ja hyvät nimet muuttujilla/sarakkeilla. En huomannut yläbannerin toimimattomuuden lisäksi koodivirheitä.

Etsintäominaisuus toimii todella hyvin!

**Comment by tire95** [comment]
Kiitos hyvästä koodikatselmoinnista. Kaikki bugit/ongelmat pitäisi nyt olla korjattu.
